/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // The JavaFX plugin handles the UI dependencies automatically now!
    // We only need your database dependency here:
    implementation("org.postgresql:postgresql:42.7.2")
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.12.1")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

javafx {
    version = "21" 
    modules("javafx.controls", "javafx.fxml", "javafx.graphics", "javafx.base")
}

application {
    // If you added 'package pos;' to your Java file, change this to "pos.DatabaseApp"
    mainClass.set("pos.DatabaseApp")
}